ALTER TABLE "WifiPlan" ADD COLUMN "featured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "WifiPlan" ADD COLUMN "manualPricing" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "WifiPlan" ADD COLUMN "imageFile" TEXT;
